### ISSUE TITLE
v1.0.4 dropped multi-target support

### ISSUE THREAD

**Issue by ManuelPombo** [mroject/freeswitch_exporter#25]
Hi,

The v1.0.4 release dropped the support for multi-target that was introduced in v1.0.2: https://github.com/mroject/freeswitch_exporter/compare/1.0.2...1.0.4#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261
I find no reference about this change in comments or release notes. 
Was this a mistake, or was any issue identified around this implementation?

Thanks

**Comment by mroject** [comment]
sorry,
in 1.0.6 fix it.
