### ISSUE TITLE
How to configure grafana to connect to 2 node Freeswitch Exporters

### ISSUE THREAD

**Issue by phamhieptel4vn** [mroject/freeswitch_exporter#28]
Configure grafana to connect to 2 node Freeswitch Exporters
Freeswitch uses port 7021, pass eventsocket is TECH2024 and Freeswitch Exporter running on 9282
Server Grafana: 192.168.100.100 
Server Freeswitch 1: 192.168.100.101
Server Freeswitch 2: 192.168.100.102

I have config target to      
    - targets:
          - '103.72.97.156:7021'
          - '119.82.130.69:7021'
  How to relabel config to separate 2 instances for monitoring?

**Comment by mroject** [comment]
PromQL can be used to distinguish between instances in prometheus. If you want to use
Grafana adds a variable and passes it as' instance 'to match.
